data:
  corpus_1:
    path_src: dataset/split_PtoR_aug5/train/src-train.txt
    path_tgt: dataset/split_PtoR_aug5/train/tgt-train.txt
  valid:
    path_src: dataset/split_PtoR_aug5/val/src-val.txt
    path_tgt: dataset/split_PtoR_aug5/val/tgt-val.txt

n_sample: -1
save_data: dataset/split_PtoR_aug5/example
src_vocab: dataset/split_PtoR_aug5/example.vocab.src
tgt_vocab: dataset/split_PtoR_aug5/example.vocab.src
share_vocab: 'true'
src_seq_length: 512
tgt_seq_length: 512
overwrite: 'true'