data:
  corpus_1:
    path_src: dataset/split_PtoR_aug5/train/src-train.txt
    path_tgt: dataset/split_PtoR_aug5/train/tgt-train.txt
  valid:
    path_src: dataset/split_PtoR_aug5/val/src-val.txt
    path_tgt: dataset/split_PtoR_aug5/val/tgt-val.txt

n_sample: 0
save_data: dataset/split_PtoR_aug5/example
src_vocab: dataset/split_PtoR_aug5/example.vocab.src
tgt_vocab: dataset/split_PtoR_aug5/example.vocab.src
share_vocab: 'true'
src_seq_length: 512
tgt_seq_length: 512
overwrite: 'true'

save_model: exp/split_PtoR_aug5_new7/model.product-reactants
save_checkpoint_steps: 10000
keep_checkpoint: 20
seed: 3435
train_steps: 1600000
valid_steps: 10000
warmup_steps: 20000
report_every: 10000
early_stopping: 10
early_stopping_criteria: accuracy

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 4
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 128
valid_batch_size: 128
batch_type: sents
normalization: sents
dropout: 0.1
attention_dropout: 0.3
label_smoothing: 0.0

max_generator_batches: 32

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks:
- 0
